version: '3.4'

services:
  api.core:
    image: ${DOCKER_REGISTRY-}apicore
    build:
      context: .
      dockerfile: Api/Api.Core/Dockerfile

  client.blazor:
    image: ${DOCKER_REGISTRY-}clientblazor
    build:
      context: .
      dockerfile: Client/Client.Blazor/Dockerfile

